name: init-aws-org-root
on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: aws access key id for initial credentials of aws org root account
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: aws secret access key for initial credentials of aws org root account
        required: true
      AWS_REGION:
        description: aws region for initial credentials of aws org root account
        required: true
        default: "us-east-1"
jobs:
  init-aws-org-root:
    name: run initialization tasks on AWS org root account
    runs-on: ubuntu-latest
    steps:
      - name: mask inputs
        run: |
          AWS_ACCESS_KEY_ID=$(jq -r '.inputs.AWS_ACCESS_KEY_ID' $GITHUB_EVENT_PATH)
          AWS_SECRET_ACCESS_KEY=$(jq -r '.inputs.AWS_SECRET_ACCESS_KEY' $GITHUB_EVENT_PATH)
          echo ::add-mask::$AWS_ACCESS_KEY_ID
          echo ::add-mask::$AWS_SECRET_ACCESS_KEY
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Print the inputs
        run: |
          echo AWS_ACCESS_KEY_ID is ${{ inputs.AWS_ACCESS_KEY_ID }}
          echo AWS_SECRET_ACCESS_KEY is ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          echo AWS_REGION is ${{ inputs.AWS_REGION }}
